runtime: custom
env: flex
service: stoa-metabase
# Metabase does not support horizontal scaling
#   https://github.com/metabase/metabase/issues/2754
#   https://cloud.google.com/appengine/docs/flexible/java/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1

env_variables:
  MB_JETTY_PORT: 8080
  MB_DB_TYPE: postgres
  MB_DB_DBNAME: metabase
  MB_DB_PORT: 5432
  MB_DB_USER: metabase
  MB_DB_PASS: C2m4V9Md97M739Tvm46
  MB_DB_HOST: 127.0.0.1
  CLOUD_SQL_INSTANCE: inspection-fund:us-east1:stoa-postgress-inspection

